In [1]:
import numpy as np

### Example 1

In [2]:
# Creating a 3 x 2 matrix
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
# Creating a vector, and broadcasting the shape
b = np.array([5, 10, 5])[:,np.newaxis]
b

array([[ 5],
       [10],
       [ 5]])

In [4]:
# Addition of matrix and a vector
A + b

array([[ 5,  6],
       [12, 13],
       [ 9, 10]])

### Example 2

In [5]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

In [7]:
A[:, -1][:, np.newaxis] + B

array([[ 7,  8],
       [11, 12]])

### The matrix product

In [8]:
A = np.array([[1, 2], [2, 3], [3, 4]])
A

array([[1, 2],
       [2, 3],
       [3, 4]])

In [9]:
B = np.array([[1, 2, 4, 5], [6, 3, 1, 2]])
B

array([[1, 2, 4, 5],
       [6, 3, 1, 2]])

In [10]:
A.dot(B)

array([[13,  8,  6,  9],
       [20, 13, 11, 16],
       [27, 18, 16, 23]])

In [11]:
# Using matmul
np.matmul(A, B)

array([[13,  8,  6,  9],
       [20, 13, 11, 16],
       [27, 18, 16, 23]])

In [12]:
mat_C = np.zeros((A.shape[0], B.shape[1]))
mat_C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Matrix multiplication
def mat_mul(mat_A, mat_B):
    mat_C = np.zeros((mat_A.shape[0], mat_B.shape[1]))
    for i in range(mat_A.shape[0]):
        for j in range(mat_B.shape[1]):
            for k in range(mat_A.shape[1]):
                mat_C[i][j] += mat_A[i][k] * mat_B[k][j]
    return mat_C

In [14]:
mat_mul(A, B)

array([[13.,  8.,  6.,  9.],
       [20., 13., 11., 16.],
       [27., 18., 16., 23.]])

<br>
The __dot product__ between two vectors $x$ and $y$ of the same dimensionality is the matrix product $x^Ty$. We can think of the matrix product $C = AB$ as computing $C_{i,j}$ as the dot product between row $i$ of $A$ and column $j$ of $B$.

\begin{equation*}
x \cdot y = (x_1 y_1 + x_2 y_2 + \ldots + x_n y_n)
\end{equation*}

In [15]:
# The dot product between two vectors
x = np.array([1, 2, 3])
y = np.array([2, 5, 10])

np.dot(x, y)

42

In [16]:
x @ y

42

In [17]:
def dot_prod(vec_a, vec_b):
    dot_product = 0
    for i, j in zip(vec_a, vec_b):
        dot_product += i * j
    return dot_product

In [18]:
dot_prod(x, y)

42

#### Identity Matrix ([numpy docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html))

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
x.dot(np.identity(3))

array([1., 2., 3.])

#### The Matrix Inverse ([numpy docs](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.inv.html))

In [21]:
from numpy.linalg import inv

In [22]:
A = np.random.randint(10, size=(3, 3))
A

array([[5, 0, 1],
       [2, 9, 9],
       [9, 6, 2]])

In [23]:
inv(A)

array([[ 0.14457831, -0.02409639,  0.03614458],
       [-0.30923695, -0.00401606,  0.17269076],
       [ 0.27710843,  0.12048193, -0.18072289]])

In [24]:
inv(A).dot(A)

array([[ 1.00000000e+00,  2.77555756e-17,  0.00000000e+00],
       [ 8.32667268e-17,  1.00000000e+00,  5.55111512e-17],
       [-1.94289029e-16, -5.55111512e-17,  1.00000000e+00]])