In [1]:
import numpy as np

### Example 1

In [2]:
# Creating a 3 x 2 matrix
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
# Creating a vector, and broadcasting the shape
b = np.array([5, 10, 5])[:,np.newaxis]
b

array([[ 5],
       [10],
       [ 5]])

In [4]:
# Addition of matrix and a vector
A + b

array([[ 5,  6],
       [12, 13],
       [ 9, 10]])

### Example 2

In [5]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

In [7]:
A[:, -1][:, np.newaxis] + B

array([[ 7,  8],
       [11, 12]])

### The matrix product

In [8]:
A = np.array([[1, 2], [2, 3], [3, 4]])
A

array([[1, 2],
       [2, 3],
       [3, 4]])

In [9]:
B = np.array([[1, 2, 4, 5], [6, 3, 1, 2]])
B

array([[1, 2, 4, 5],
       [6, 3, 1, 2]])

In [10]:
A.dot(B)

array([[13,  8,  6,  9],
       [20, 13, 11, 16],
       [27, 18, 16, 23]])

In [11]:
# Using matmul
np.matmul(A, B)

array([[13,  8,  6,  9],
       [20, 13, 11, 16],
       [27, 18, 16, 23]])

In [12]:
mat_C = np.zeros((A.shape[0], B.shape[1]))
mat_C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Matrix multiplication
def mat_mul(mat_A, mat_B):
    mat_C = np.zeros((mat_A.shape[0], mat_B.shape[1]))
    for i in range(mat_A.shape[0]):
        for j in range(mat_B.shape[1]):
            for k in range(mat_A.shape[1]):
                mat_C[i][j] += mat_A[i][k] * mat_B[k][j]
    return mat_C

In [14]:
mat_mul(A, B)

array([[13.,  8.,  6.,  9.],
       [20., 13., 11., 16.],
       [27., 18., 16., 23.]])

<br>
The __dot product__ between two vectors $x$ and $y$ of the same dimensionality is the matrix product $x^Ty$. We can think of the matrix product $C = AB$ as computing $C_{i,j}$ as the dot product between row $i$ of $A$ and column $j$ of $B$.

\begin{equation*}
x \cdot y = (x_1 y_1 + x_2 y_2 + \ldots + x_n y_n)
\end{equation*}

In [15]:
# The dot product between two vectors
x = np.array([1, 2, 3])
y = np.array([2, 5, 10])

np.dot(x, y)

42

In [16]:
x @ y

42

In [17]:
def dot_prod(vec_a, vec_b):
    dot_product = 0
    for i, j in zip(vec_a, vec_b):
        dot_product += i * j
    return dot_product

In [18]:
dot_prod(x, y)

42

#### Identity Matrix ([numpy docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html))

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
x.dot(np.identity(3))

array([1., 2., 3.])

#### The Matrix Inverse ([numpy docs](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.inv.html))

In [21]:
from numpy.linalg import inv

In [22]:
A = np.random.randint(10, size=(3, 3))
A

array([[6, 4, 6],
       [4, 4, 4],
       [3, 1, 0]])

In [23]:
inv(A)

array([[ 0.16666667, -0.25      ,  0.33333333],
       [-0.5       ,  0.75      ,  0.        ],
       [ 0.33333333, -0.25      , -0.33333333]])

In [24]:
inv(A).dot(A)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 4.44089210e-16,  1.00000000e+00,  4.44089210e-16],
       [-1.66533454e-16, -5.55111512e-17,  1.00000000e+00]])

<br>
#### Norms ([numpy docs](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.norm.html))

* For the Euclidean Norm, $L^2$ norm, $\|x\|_2 = \sqrt{x^2_1 + x^2_2 + \ldots + x^2_n}$  
* If $x$ is a column vector, then $\|x\|_2 = \sqrt{x^Tx}$  
* $L^1$ norm, $\|x\|_1 = \displaystyle\sum_{i}{\lvert x_i \lvert}$  
* Max norm, $L^\infty$ norm, $\|x\|_\infty = \max\limits_{i}{\lvert x_i \lvert}$  
* Frobenius norm, in ML context to measure the size of matrix, $\|A\|_F = \sqrt{\displaystyle\sum_{i, j}{A^2_{i, j}}}$  

In [33]:
from numpy.linalg import norm
vect = np.random.randint(10, size=3)
vect

array([6, 3, 4])

In [34]:
norm(vect)

7.810249675906654

In [35]:
(vect[0]**2 + vect[1]**2 + vect[2]**2)**0.5

7.810249675906654

In [36]:
np.sqrt(vect.dot(vect))

7.810249675906654

In [37]:
# L1 norm
norm(vect, ord=1)

13.0

In [40]:
# Linf norm
norm(vect, ord=np.inf)

6.0

In [42]:
# Frobenius norm
norm(A, ord='fro')

12.083045973594572