## Deep Learning
### Chapter 2. Linear Algebra - Notes and Examples

In [1]:
# Importing numpy library
import numpy as np

#### Addition of matrix and a vector
#### Example 1

In [2]:
# Creating a 3 x 2 matrix
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
# Creating a vector, and broadcasting the shape
b = np.array([5, 10, 5])[:,np.newaxis]
b

array([[ 5],
       [10],
       [ 5]])

In [4]:
# Addition of matrix and a vector
A + b

array([[ 5,  6],
       [12, 13],
       [ 9, 10]])

#### Example 2

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [6]:
# Using a vector from a matrix
A[:, -1][:, np.newaxis] + B

array([[ 7,  8],
       [11, 12]])

#### The matrix product ([numpy docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html))

In [7]:
A = np.array([[1, 2], [2, 3], [3, 4]])
B = np.array([[1, 2, 4, 5], [6, 3, 1, 2]])

In [8]:
# Using numpy.dot method
A.dot(B)

array([[13,  8,  6,  9],
       [20, 13, 11, 16],
       [27, 18, 16, 23]])

In [9]:
# Using matmul
np.matmul(A, B)

array([[13,  8,  6,  9],
       [20, 13, 11, 16],
       [27, 18, 16, 23]])

<br>
Manually creating a method for matrix product:

In [10]:
# Matrix multiplication
def mat_mul(mat_A, mat_B):
    mat_C = np.zeros((mat_A.shape[0], mat_B.shape[1]))
    for i in range(mat_A.shape[0]):
        for j in range(mat_B.shape[1]):
            for k in range(mat_A.shape[1]):
                mat_C[i][j] += mat_A[i][k] * mat_B[k][j]
    return mat_C

In [11]:
mat_mul(A, B)

array([[13.,  8.,  6.,  9.],
       [20., 13., 11., 16.],
       [27., 18., 16., 23.]])

<br>
The __dot product__ between two vectors $x$ and $y$ of the same dimensionality is the matrix product $x^Ty$. We can think of the matrix product $C = AB$ as computing $C_{i,j}$ as the dot product between row $i$ of $A$ and column $j$ of $B$.

\begin{equation*}
x \cdot y = (x_1 y_1 + x_2 y_2 + \ldots + x_n y_n)
\end{equation*}

In [12]:
# The dot product between two vectors
x = np.array([1, 2, 3])
y = np.array([2, 5, 10])

np.dot(x, y)

42

In [13]:
x @ y

42

In [14]:
# Manually creating dot product function
def dot_prod(vec_a, vec_b):
    dot_product = 0
    for i, j in zip(vec_a, vec_b):
        dot_product += i * j
    return dot_product

In [15]:
dot_prod(x, y)

42

#### Identity Matrix ([numpy docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html))

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
x.dot(np.identity(3))

array([1., 2., 3.])

#### The Matrix Inverse ([numpy docs](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.inv.html))

In [18]:
from numpy.linalg import inv

In [19]:
A = np.random.randint(10, size=(3, 3))
A

array([[9, 5, 5],
       [0, 6, 3],
       [6, 3, 5]])

In [20]:
inv(A)

array([[ 0.21212121, -0.1010101 , -0.15151515],
       [ 0.18181818,  0.15151515, -0.27272727],
       [-0.36363636,  0.03030303,  0.54545455]])

In [21]:
inv(A).dot(A)

array([[1.00000000e+00, 1.11022302e-16, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

<br>
#### Norms ([numpy docs](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.norm.html))

* For the Euclidean Norm, $L^2$ norm, $\|x\|_2 = \sqrt{x^2_1 + x^2_2 + \ldots + x^2_n}$  
* If $x$ is a column vector, then $\|x\|_2 = \sqrt{x^Tx}$  
* $L^1$ norm, $\|x\|_1 = \displaystyle\sum_{i}{\lvert x_i \lvert}$  
* Max norm, $L^\infty$ norm, $\|x\|_\infty = \max\limits_{i}{\lvert x_i \lvert}$  
* Frobenius norm, in ML context to measure the size of matrix, $\|A\|_F = \sqrt{\displaystyle\sum_{i, j}{A^2_{i, j}}}$  

In [22]:
from numpy.linalg import norm
vect = np.random.randint(10, size=3)
vect

array([3, 5, 8])

In [23]:
norm(vect)

9.899494936611665

In [24]:
(vect[0]**2 + vect[1]**2 + vect[2]**2)**0.5

9.899494936611665

In [25]:
np.sqrt(vect.dot(vect))

9.899494936611665

In [26]:
# L1 norm
norm(vect, ord=1)

16.0

In [27]:
# Linf norm
norm(vect, ord=np.inf)

8.0

In [28]:
# Frobenius norm
norm(A, ord='fro')

15.684387141358123